Add ECDSA key support (SECP256R1) again
biscuit-auth/biscuit-java pull request #108
Opened 2024-11-26 18:29 UTC by itstheceo

Supersedes https://github.com/biscuit-auth/biscuit-java/pull/101

Had some difficulties syncing latest on the other PR, because the fork got disconnected from upstream when my organisation did a bulk visibility change across all repositories. Have just done in my personal account, same branch as before but synced with upstream.

Uses BouncyCastle for the provider. Any feedback greatly appreciated. Thanks!

2025-01-15 09:59 UTC, Korbik requested changes
I will try to use the sample from the new specification

2025-01-15 09:59 UTC, Korbik commented on src/main/java/org/biscuitsec/biscuit/crypto/Ed25519KeyPair.java
> +class Ed25519KeyPair extends KeyPair {
```suggestion
final class Ed25519KeyPair extends KeyPair {
```

2025-01-15 09:59 UTC, Korbik commented on pom.xml
> +            <version>1.78.1</version>
```suggestion
            <version>1.79</version>
```
Do we bump the version of Bouncy ?

2025-01-15 09:59 UTC, Korbik commented on src/main/java/org/biscuitsec/biscuit/crypto/SECP256R1KeyPair.java
> +class SECP256R1KeyPair extends KeyPair {
```suggestion
final class SECP256R1KeyPair extends KeyPair {
```

2025-01-15 09:59 UTC, Korbik commented on src/main/java/org/biscuitsec/biscuit/token/format/SerializedBiscuit.java
> +            if (signature.length != 64) {
Could be an improvement to replace it by a constant.

2025-01-15 09:59 UTC, Korbik commented on src/main/java/org/biscuitsec/biscuit/token/format/SerializedBiscuit.java
> +            if (signature.length < 68 || signature.length > 72) {
Could be an improvement to replace it by a constant.

2025-01-15 09:59 UTC, Korbik commented on src/main/java/org/biscuitsec/biscuit/token/UnverifiedBiscuit.java
> +        var result = serializedBiscuit.verify(publicKey);
Good catch, I will check the impact to remove vavr in the future. It is not the best fit for our purpose.

2025-01-15 13:54 UTC, Korbik commented
The failing test from the specification is linked to this PR https://github.com/biscuit-auth/biscuit/pull/175

2025-01-16 00:07 UTC, itstheceo commented
> The failing test from the specification is linked to this PR [biscuit-auth/biscuit#175](https://github.com/biscuit-auth/biscuit/pull/175)

Thanks for the review, will address those comments 🚀 

Regarding the test you updated; is that `test036_secp256r1.bc` signed with the v1 signature format, and the implementation needs updating to handle that?

2025-01-16 10:05 UTC, Korbik commented
> > The failing test from the specification is linked to this PR [biscuit-auth/biscuit#175](https://github.com/biscuit-auth/biscuit/pull/175)
> 
> Thanks for the review, will address those comments 🚀
> 
> Regarding the test you updated; is that `test036_secp256r1.bc` signed with the v1 signature format, and the implementation needs updating to handle that?

Yes, it is necessary to update the signature and verification of the signature. We have also a new format of protobuf message. Let me know if you want me to care of it or prefer to implement it yourself.

2025-01-17 00:25 UTC, itstheceo commented
> > > The failing test from the specification is linked to this PR [biscuit-auth/biscuit#175](https://github.com/biscuit-auth/biscuit/pull/175)
> > 
> > 
> > Thanks for the review, will address those comments 🚀
> > Regarding the test you updated; is that `test036_secp256r1.bc` signed with the v1 signature format, and the implementation needs updating to handle that?
> 
> Yes, it is necessary to update the signature and verification of the signature. We have also a new format of protobuf message. Let me know if you want me to care of it or prefer to implement it yourself.

Updating the Java implementation to the latest Biscuit spec feels like a separate task from adding support for ECDSA keys, and should be in it's own PR. I have updated `test036_secp256r1.bc` from the rust PR equivalent for ECDSA key support https://github.com/biscuit-auth/biscuit-rust/pull/108

2025-01-17 09:53 UTC, divarvel commented
agreed that is a separate task. we will need to carry it out right away because as of now in biscuit-rust, the use of P256 triggers the use of v1 signatures.

2025-01-17 15:49 UTC, merged