samples verify block by block
biscuit-auth/biscuit-java pull request #88
Opened 2024-04-08 15:35 UTC by KannarFr

This is DRAFT.

2024-04-14 15:38 UTC, Geal requested changes

2024-04-14 15:38 UTC, Geal commented on src/main/java/org/biscuitsec/biscuit/token/Block.java
> +        System.out.println(b.getScopeList());
(just flagging that this will need to be removed because we tend to forget about printlns in this project)

2024-04-14 15:38 UTC, Geal commented on src/main/java/org/biscuitsec/biscuit/token/builder/parser/Parser.java
> +        Stream.of(codeLines).zipWithIndex().forEach(indexedLine -> {
if the empty lines are filtered (on line 56), the the index given here will have the wrong line number (if you intend to use the index somewhere)

2024-04-14 15:38 UTC, Geal commented on src/main/java/org/biscuitsec/biscuit/token/builder/parser/Parser.java
> +            }
this looks brittle. In general here we would try them one after the other if they error out, and stop at the first one that matches

2024-04-14 15:38 UTC, Geal commented on src/main/java/org/biscuitsec/biscuit/token/builder/parser/Parser.java
> +        long i = Long.parseLong(s.substring(0, index2));
nice catch

2024-04-14 15:38 UTC, Geal commented on src/main/java/org/biscuitsec/biscuit/token/builder/parser/Parser.java
> +    }
this should be rewritten as a parser combinator in the same style as the rest. I get the temptation to do a quick and easy loop, but that will create problems down the line if we want to make the parser a bit smarter

2024-04-14 15:38 UTC, Geal commented on src/test/java/org/biscuitsec/biscuit/builder/parser/ParserTest.java
> +        assertEquals(Either.right(new Tuple2<>("",
this fails in https://github.com/biscuit-auth/biscuit-java/actions/runs/8622173639/job/23632740026?pr=88#step:5:6256
```
ParserTest.expressionIntersectionAndContainsTest:141 expected: <Right((, [1, 2, 3].intersection([1, 2]).contains(1)))> but was: <Right((.contains(1), [1, 2, 3].intersection([1, 2])))>
```

Probably because this function is mission a loop:
https://github.com/biscuit-auth/biscuit-java/blob/53be7b952dac15d1d2de3c112d998b4d34917c46/src/main/java/org/biscuitsec/biscuit/token/builder/parser/ExpressionParser.java#L308-L343

cf the next level of precedence where the loop is present:

https://github.com/biscuit-auth/biscuit-java/blob/53be7b952dac15d1d2de3c112d998b4d34917c46/src/main/java/org/biscuitsec/biscuit/token/builder/parser/ExpressionParser.java#L262-L301

2024-04-14 15:38 UTC, Geal commented on src/test/java/org/biscuitsec/biscuit/token/SamplesTest.java
> +        assertTrue(outputSample.isRight());
this should show the input that was parsed and the error we got, otherwise we don't have any context to fix it

2024-04-14 15:38 UTC, Geal commented on src/test/java/org/biscuitsec/biscuit/token/SamplesTest.java
> +        assertArrayEquals(outputSample.get().build().to_bytes().get(), block.to_bytes().get());
same here, this should show the expected and actual arrays, because the errors don't help https://github.com/biscuit-auth/biscuit-java/actions/runs/8622173639/job/23632740026?pr=88#step:5:6259

2024-04-14 15:38 UTC, Geal commented on src/test/java/org/biscuitsec/biscuit/token/SamplesTest.java
> +                        return new PublicKey(Schema.PublicKey.Algorithm.Ed25519, parts[1]);
this should use the existing public key parser because we will soon add other key types
https://github.com/biscuit-auth/biscuit-java/blob/53be7b952dac15d1d2de3c112d998b4d34917c46/src/main/java/org/biscuitsec/biscuit/token/builder/parser/Parser.java#L321-L328

2024-04-14 15:38 UTC, Geal commented on src/test/java/org/biscuitsec/biscuit/token/SamplesTest.java
> +                return Option.of(new PublicKey(Schema.PublicKey.Algorithm.Ed25519, parts[1]));
same here, this should use the existing public key parser

2024-04-14 15:39 UTC, Geal commented
BTW is there a good way in maven to capture stdout in tests, so that we only display it for tests that failed?

2024-04-27 21:27 UTC, murdos commented on src/main/java/org/biscuitsec/biscuit/datalog/SymbolTable.java
> +        this.symbols = new ArrayList<>();
you can init directly the list:
```suggestion
        this.symbols = new ArrayList<>(symbols);
```

2024-05-01 12:15 UTC, murdos commented on src/main/java/org/biscuitsec/biscuit/datalog/SymbolTable.java
> +        this.symbols.addAll(symbols);
```suggestion
```

2024-05-01 12:40 UTC, Geal commented
https://github.com/biscuit-auth/biscuit-java/pull/94 merges the parts of this PR that were already usable, leaving the saples block checks and the `Parser.datalog` method.

Right now I am not too convinced about the implementation of that method that does manual string manipulations. An implementation that follows the rest of the parser, using parser combinators, would fit better here and prevent errors.
The Rust reference implementation can be used as inspiration here https://github.com/biscuit-auth/biscuit-rust/blob/main/biscuit-parser/src/parser.rs#L895-L970

2024-06-15 15:27 UTC, Geal commented
closing this since it has been merged as part of https://github.com/biscuit-auth/biscuit-java/pull/102

2024-06-15 15:27 UTC, closed without merging